
#ifndef ROSA_TRANSPORT_SECURITY_KEY_AGREEMENT_HANDLER_H_
#define ROSA_TRANSPORT_SECURITY_KEY_AGREEMENT_HANDLER_H_

class key_agreement_handler {

};

#endif //ROSA_TRANSPORT_SECURITY_KEY_AGREEMENT_HANDLER_H_
